### ISSUE TITLE
Standard yarn package install fails

### ISSUE THREAD

**Issue by mjstelly** [BigstickCarpet/static-mock-data#1]
I installed this package with `yarn`. No install errors. But, when I try to either `require()` it or `import` it, I get the following error:
`error: bundling failed: Error: Unable to resolve module 'path' from '/Users/me/Documents/projects/myproj/node_modules/static-mock-data/lib/node.js' : Module does not exist in the module map`
I cleared watchman. I deleted and reinstalled `node_modules`. Same result. If I remove the call to `static-mock-data`, the app works normally again.

So I think I can say with confidence that something is broken with the package. But, I could be wrong. Thought I'd post it as an issue.

Thanks.

**Comment by BigstickCarpet** [comment]
It sounds like you're trying to use it on a web page, but trying to import the Node.js module rather than the web distributable.  See the [instructions in the ReadMe](https://github.com/BigstickCarpet/static-mock-data#usage-in-web-browsers) for details.

**Comment by BigstickCarpet** [comment]
I've [added a `"browser"` property to the package.json file](https://github.com/BigstickCarpet/static-mock-data/commit/e3ba67a25fd711e451d5bbd54fdf1b009a106650) to help with bundler tools, such as Webpack, Rollup, Browserify, etc.   It might help in your case, if you're using a bundler that supports the `"browser"` property.  Try upgrading to v3.2.9 and see if that helps.

**Comment by mjstelly** [comment]
No, I'm trying to use it in a react-native app.

**Comment by BigstickCarpet** [comment]
I've never done react-native, but AFAIK the JavaScript engine runs in a browser scripting host and thus doesn't have access to Node.js APIs.  Thus you'll need to use the browser distributable rather than the Node.js module.

**Comment by mjstelly** [comment]
No worries. I've found an alternative react-native based solution. Thanks for your feedback.
